sudo: required
dist: trusty

language: java
jdk:
  - openjdk8
  - oraclejdk8

env: GRADLE_OPTS="-Xms1g -Xmx3g"
before_install: chmod +x gradlew
install: true
script: ./gradlew

notifications:
  email: false